# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8bf34032063d372387504b352c35aed28d08eb7dcffebd038154c74c8a0786aad0f5f8330e9caee70250ca8584f974ac6fc1b7c58f1241b0104e7bcf2f7491

test:
  secret_key_base: 57d63900cacdbec91e4c39579882215b91ca4e94ac7ac2b99e9006c3c5fb07ac753e812f787834d60eb051d39bbab39f15a1f41cf243172ba0fed464cac1bc80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
